require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConfigurableParamsController do
  before do
    @admin_user = get_admin_user
  end

  # This should return the minimal set of attributes required to create a valid
  # ConfigurableParam. As you add validations to ConfigurableParam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "param" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConfigurableParamsController. Be sure to keep this updated too.
  def valid_session
    { :user_id => @admin_user.id}
  end

  describe "GET index" do
    it "assigns all configurable_params as @configurable_params" do
      configurable_param = ConfigurableParam.create! valid_attributes
      get :index, {}, valid_session
      assigns(:configurable_params).should eq([configurable_param])
    end
  end

  describe "GET show" do
    it "assigns the requested configurable_param as @configurable_param" do
      configurable_param = ConfigurableParam.create! valid_attributes
      get :show, {:id => configurable_param.to_param}, valid_session
      assigns(:configurable_param).should eq(configurable_param)
    end
  end

  describe "GET new" do
    it "assigns a new configurable_param as @configurable_param" do
      get :new, {}, valid_session
      assigns(:configurable_param).should be_a_new(ConfigurableParam)
    end
  end

  describe "GET edit" do
    it "assigns the requested configurable_param as @configurable_param" do
      configurable_param = ConfigurableParam.create! valid_attributes
      get :edit, {:id => configurable_param.to_param}, valid_session
      assigns(:configurable_param).should eq(configurable_param)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConfigurableParam" do
        expect {
          post :create, {:configurable_param => valid_attributes}, valid_session
        }.to change(ConfigurableParam, :count).by(1)
      end

      it "assigns a newly created configurable_param as @configurable_param" do
        post :create, {:configurable_param => valid_attributes}, valid_session
        assigns(:configurable_param).should be_a(ConfigurableParam)
        assigns(:configurable_param).should be_persisted
      end

      it "redirects to the created configurable_param" do
        post :create, {:configurable_param => valid_attributes}, valid_session
        response.should redirect_to(ConfigurableParam.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved configurable_param as @configurable_param" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConfigurableParam.any_instance.stub(:save).and_return(false)
        post :create, {:configurable_param => { "param" => "invalid value" }}, valid_session
        assigns(:configurable_param).should be_a_new(ConfigurableParam)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConfigurableParam.any_instance.stub(:save).and_return(false)
        post :create, {:configurable_param => { "param" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested configurable_param" do
        configurable_param = ConfigurableParam.create! valid_attributes
        # Assuming there are no other configurable_params in the database, this
        # specifies that the ConfigurableParam created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConfigurableParam.any_instance.should_receive(:update_attributes).with({ "param" => "MyString" })
        put :update, {:id => configurable_param.to_param, :configurable_param => { "param" => "MyString" }}, valid_session
      end

      it "assigns the requested configurable_param as @configurable_param" do
        configurable_param = ConfigurableParam.create! valid_attributes
        put :update, {:id => configurable_param.to_param, :configurable_param => valid_attributes}, valid_session
        assigns(:configurable_param).should eq(configurable_param)
      end

      it "redirects to the configurable_param" do
        configurable_param = ConfigurableParam.create! valid_attributes
        put :update, {:id => configurable_param.to_param, :configurable_param => valid_attributes}, valid_session
        response.should redirect_to(configurable_param)
      end
    end

    describe "with invalid params" do
      it "assigns the configurable_param as @configurable_param" do
        configurable_param = ConfigurableParam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConfigurableParam.any_instance.stub(:save).and_return(false)
        put :update, {:id => configurable_param.to_param, :configurable_param => { "param" => "invalid value" }}, valid_session
        assigns(:configurable_param).should eq(configurable_param)
      end

      it "re-renders the 'edit' template" do
        configurable_param = ConfigurableParam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConfigurableParam.any_instance.stub(:save).and_return(false)
        put :update, {:id => configurable_param.to_param, :configurable_param => { "param" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested configurable_param" do
      configurable_param = ConfigurableParam.create! valid_attributes
      expect {
        delete :destroy, {:id => configurable_param.to_param}, valid_session
      }.to change(ConfigurableParam, :count).by(-1)
    end

    it "redirects to the configurable_params list" do
      configurable_param = ConfigurableParam.create! valid_attributes
      delete :destroy, {:id => configurable_param.to_param}, valid_session
      response.should redirect_to(configurable_params_url)
    end
  end

end
