require 'spec_helper'
# ========================================================================
# !!!!!TODO Note that this test was generated for table named HmmDBHit but
# has been altered since that table will be renamed to DBEntry.
# Go over the test and change references to HmmDBHit when renaming is done
# ========================================================================

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

 describe DbEntriesController do
  let!(:db_sequence) { FactoryGirl.create(:db_sequence)}
  let!(:db_entry) { FactoryGirl.create(:db_entry, db_sequence: db_sequence) }
  before do
    @user = get_admin_user
  end
  #This should return the minimal set of attributes required to create a vali
  #DbEntry. As you add validations to DbEntry, be sure to
  #update the return value of this method accordingly.
  def valid_attributes
    {gi: '1234', db_sequence_id: db_sequence.id}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DbEntriesController. Be sure to keep this updated too.
  def valid_session
    {:user_id => @user}
  end

  describe "GET index" do
    it "assigns all db_entries as @db_entries" do
      get :index, {}, valid_session
      assigns(:db_entries).should eq([db_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested db_entry as @db_entry" do
      get :show, {:id => db_entry.to_param}, valid_session
      assigns(:db_entry).should eq(db_entry)
    end
  end

  describe "GET new" do
    it "assigns a new db_entry as @db_entry" do
      get :new, {}, valid_session
      assigns(:db_entry).should be_a_new(DbEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested db_entry as @db_entry" do
      get :edit, {:id => db_entry.to_param}, valid_session
      assigns(:db_entry).should eq(db_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DbEntry" do
        expect {
          post :create, {db_entry: valid_attributes}, valid_session
        }.to change(DbEntry, :count).by(1)
      end

      it "assigns a newly created db_entry as @db_entry" do
        post :create, {:db_entry => valid_attributes}, valid_session
        assigns(:db_entry).should be_a(DbEntry)
        assigns(:db_entry).should be_persisted
      end

      it "redirects to the created db_entry" do
        post :create, {:db_entry => valid_attributes}, valid_session
        response.should redirect_to(DbEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved db_entry as @db_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        DbEntry.any_instance.stub(:save).and_return(false)
        post :create, {:db_entry => {}}, valid_session
        assigns(:db_entry).should be_a_new(DbEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DbEntry.any_instance.stub(:save).and_return(false)
        post :create, {:db_entry => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested db_entry" do
        db_entry = DbEntry.create! valid_attributes
        # Assuming there are no other db_entries in the database, this
        # specifies that the DbEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DbEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => db_entry.to_param, :db_entry => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested db_entrycontrollers/db_entries_controller_spec.rb as @db_entry" do
        db_entry = DbEntry.create! valid_attributes
        put :update, {:id => db_entry.to_param, :db_entry => valid_attributes}, valid_session
        assigns(:db_entry).should eq(db_entry)
      end

      it "redirects to the db_entry" do
        db_entry = DbEntry.create! valid_attributes
        put :update, {:id => db_entry.to_param, :db_entry => valid_attributes}, valid_session
        response.should redirect_to(db_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the db_entry as @db_entry" do
        db_entry = DbEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DbEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => db_entry.to_param, :db_entry => {}}, valid_session
        assigns(:db_entry).should eq(db_entry)
      end

      it "re-renders the 'edit' template" do
        db_entry = DbEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DbEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => db_entry.to_param, :db_entry => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested db_entry" do
      db_entry = DbEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => db_entry.to_param}, valid_session
      }.to change(DbEntry, :count).by(-1)
    end

    it "redirects to the db_entries list" do
      db_entry = DbEntry.create! valid_attributes
      delete :destroy, {:id => db_entry.to_param}, valid_session
      response.should redirect_to(db_entries_url)
    end
  end

end
