require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HmmDbHitsController do

  # This should return the minimal set of attributes required to create a valid
  # HmmDbHit. As you add validations to HmmDbHit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HmmDbHitsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hmm_db_hits as @hmm_db_hits" do
      hmm_db_hit = HmmDbHit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hmm_db_hits).should eq([hmm_db_hit])
    end
  end

  describe "GET show" do
    it "assigns the requested hmm_db_hit as @hmm_db_hit" do
      hmm_db_hit = HmmDbHit.create! valid_attributes
      get :show, {:id => hmm_db_hit.to_param}, valid_session
      assigns(:hmm_db_hit).should eq(hmm_db_hit)
    end
  end

  describe "GET new" do
    it "assigns a new hmm_db_hit as @hmm_db_hit" do
      get :new, {}, valid_session
      assigns(:hmm_db_hit).should be_a_new(HmmDbHit)
    end
  end

  describe "GET edit" do
    it "assigns the requested hmm_db_hit as @hmm_db_hit" do
      hmm_db_hit = HmmDbHit.create! valid_attributes
      get :edit, {:id => hmm_db_hit.to_param}, valid_session
      assigns(:hmm_db_hit).should eq(hmm_db_hit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HmmDbHit" do
        expect {
          post :create, {:hmm_db_hit => valid_attributes}, valid_session
        }.to change(HmmDbHit, :count).by(1)
      end

      it "assigns a newly created hmm_db_hit as @hmm_db_hit" do
        post :create, {:hmm_db_hit => valid_attributes}, valid_session
        assigns(:hmm_db_hit).should be_a(HmmDbHit)
        assigns(:hmm_db_hit).should be_persisted
      end

      it "redirects to the created hmm_db_hit" do
        post :create, {:hmm_db_hit => valid_attributes}, valid_session
        response.should redirect_to(HmmDbHit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hmm_db_hit as @hmm_db_hit" do
        # Trigger the behavior that occurs when invalid params are submitted
        HmmDbHit.any_instance.stub(:save).and_return(false)
        post :create, {:hmm_db_hit => {}}, valid_session
        assigns(:hmm_db_hit).should be_a_new(HmmDbHit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HmmDbHit.any_instance.stub(:save).and_return(false)
        post :create, {:hmm_db_hit => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hmm_db_hit" do
        hmm_db_hit = HmmDbHit.create! valid_attributes
        # Assuming there are no other hmm_db_hits in the database, this
        # specifies that the HmmDbHit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HmmDbHit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => hmm_db_hit.to_param, :hmm_db_hit => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested hmm_db_hit as @hmm_db_hit" do
        hmm_db_hit = HmmDbHit.create! valid_attributes
        put :update, {:id => hmm_db_hit.to_param, :hmm_db_hit => valid_attributes}, valid_session
        assigns(:hmm_db_hit).should eq(hmm_db_hit)
      end

      it "redirects to the hmm_db_hit" do
        hmm_db_hit = HmmDbHit.create! valid_attributes
        put :update, {:id => hmm_db_hit.to_param, :hmm_db_hit => valid_attributes}, valid_session
        response.should redirect_to(hmm_db_hit)
      end
    end

    describe "with invalid params" do
      it "assigns the hmm_db_hit as @hmm_db_hit" do
        hmm_db_hit = HmmDbHit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HmmDbHit.any_instance.stub(:save).and_return(false)
        put :update, {:id => hmm_db_hit.to_param, :hmm_db_hit => {}}, valid_session
        assigns(:hmm_db_hit).should eq(hmm_db_hit)
      end

      it "re-renders the 'edit' template" do
        hmm_db_hit = HmmDbHit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HmmDbHit.any_instance.stub(:save).and_return(false)
        put :update, {:id => hmm_db_hit.to_param, :hmm_db_hit => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hmm_db_hit" do
      hmm_db_hit = HmmDbHit.create! valid_attributes
      expect {
        delete :destroy, {:id => hmm_db_hit.to_param}, valid_session
      }.to change(HmmDbHit, :count).by(-1)
    end

    it "redirects to the hmm_db_hits list" do
      hmm_db_hit = HmmDbHit.create! valid_attributes
      delete :destroy, {:id => hmm_db_hit.to_param}, valid_session
      response.should redirect_to(hmm_db_hits_url)
    end
  end

end
