require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LoadableDbsController do
  before do
    @user = get_admin_user
  end

  # This should return the minimal set of attributes required to create a valid
  # LoadableDb. As you add validations to LoadableDb, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      db: 'ref',
      common_name: 'RefSeq',
      genome_sequenced: true,
      default: true
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LoadableDbsController. Be sure to keep this updated too.
  def valid_session
    { user_id: @user.id }
  end

  describe "GET index" do
    it "assigns all loadable_dbs as @loadable_dbs" do
      loadable_db = LoadableDb.create! valid_attributes
      get :index, {}, valid_session
      assigns(:loadable_dbs).should eq([loadable_db])
    end
  end

  describe "GET show" do
    it "assigns the requested loadable_db as @loadable_db" do
      loadable_db = LoadableDb.create! valid_attributes
      get :show, {:id => loadable_db.to_param}, valid_session
      assigns(:loadable_db).should eq(loadable_db)
    end
  end

  describe "GET new" do
    it "assigns a new loadable_db as @loadable_db" do
      get :new, {}, valid_session
      assigns(:loadable_db).should be_a_new(LoadableDb)
    end
  end

  describe "GET edit" do
    it "assigns the requested loadable_db as @loadable_db" do
      loadable_db = LoadableDb.create! valid_attributes
      get :edit, {:id => loadable_db.to_param}, valid_session
      assigns(:loadable_db).should eq(loadable_db)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LoadableDb" do
        expect {
          post :create, {:loadable_db => valid_attributes}, valid_session
        }.to change(LoadableDb, :count).by(1)
      end

      it "assigns a newly created loadable_db as @loadable_db" do
        post :create, {:loadable_db => valid_attributes}, valid_session
        assigns(:loadable_db).should be_a(LoadableDb)
        assigns(:loadable_db).should be_persisted
      end

      it "redirects to the created loadable_db" do
        post :create, {:loadable_db => valid_attributes}, valid_session
        response.should redirect_to(LoadableDb.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved loadable_db as @loadable_db" do
        # Trigger the behavior that occurs when invalid params are submitted
        LoadableDb.any_instance.stub(:save).and_return(false)
        post :create, {:loadable_db => {}}, valid_session
        assigns(:loadable_db).should be_a_new(LoadableDb)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LoadableDb.any_instance.stub(:save).and_return(false)
        post :create, {:loadable_db => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested loadable_db" do
        loadable_db = LoadableDb.create! valid_attributes
        # Assuming there are no other loadable_dbs in the database, this
        # specifies that the LoadableDb created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LoadableDb.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => loadable_db.to_param, :loadable_db => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested loadable_db as @loadable_db" do
        loadable_db = LoadableDb.create! valid_attributes
        put :update, {:id => loadable_db.to_param, :loadable_db => valid_attributes}, valid_session
        assigns(:loadable_db).should eq(loadable_db)
      end

      it "redirects to the loadable_db" do
        loadable_db = LoadableDb.create! valid_attributes
        put :update, {:id => loadable_db.to_param, :loadable_db => valid_attributes}, valid_session
        response.should redirect_to(loadable_db)
      end
    end

    describe "with invalid params" do
      it "assigns the loadable_db as @loadable_db" do
        loadable_db = LoadableDb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LoadableDb.any_instance.stub(:save).and_return(false)
        put :update, {:id => loadable_db.to_param, :loadable_db => {}}, valid_session
        assigns(:loadable_db).should eq(loadable_db)
      end

      it "re-renders the 'edit' template" do
        loadable_db = LoadableDb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LoadableDb.any_instance.stub(:save).and_return(false)
        put :update, {:id => loadable_db.to_param, :loadable_db => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested loadable_db" do
      loadable_db = LoadableDb.create! valid_attributes
      expect {
        delete :destroy, {:id => loadable_db.to_param}, valid_session
      }.to change(LoadableDb, :count).by(-1)
    end

    it "redirects to the loadable_dbs list" do
      loadable_db = LoadableDb.create! valid_attributes
      delete :destroy, {:id => loadable_db.to_param}, valid_session
      response.should redirect_to(loadable_dbs_url)
    end
  end

end
