require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LoadDatabasesController do
  before do
    @user = get_admin_user
  end
  # This should return the minimal set of attributes required to create a valid
  # LoadDatabase. As you add validations to LoadDatabase, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "taxonset" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LoadDatabasesController. Be sure to keep this updated too.
  let(:valid_session) { {user_id: @user.id} }

  describe "GET index" do
    it "assigns all load_databases as @load_databases" do
      load_database = LoadDatabase.create! valid_attributes
      get :index, {}, valid_session
      assigns(:load_databases).should eq([load_database])
    end
  end

  describe "GET show" do
    it "assigns the requested load_database as @load_database" do
      load_database = LoadDatabase.create! valid_attributes
      get :show, {:id => load_database.to_param}, valid_session
      assigns(:load_database).should eq(load_database)
    end
  end

  describe "GET new" do
    it "assigns a new load_database as @load_database" do
      get :new, {}, valid_session
      assigns(:load_database).should be_a_new(LoadDatabase)
    end
  end

  describe "GET edit" do
    it "assigns the requested load_database as @load_database" do
      load_database = LoadDatabase.create! valid_attributes
      get :edit, {:id => load_database.to_param}, valid_session
      assigns(:load_database).should eq(load_database)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LoadDatabase" do
        expect {
          post :create, {:load_database => valid_attributes}, valid_session
        }.to change(LoadDatabase, :count).by(1)
      end

      it "assigns a newly created load_database as @load_database" do
        post :create, {:load_database => valid_attributes}, valid_session
        assigns(:load_database).should be_a(LoadDatabase)
        assigns(:load_database).should be_persisted
      end

      it "redirects to the created load_database" do
        post :create, {:load_database => valid_attributes}, valid_session
        response.should redirect_to(LoadDatabase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved load_database as @load_database" do
        # Trigger the behavior that occurs when invalid params are submitted
        LoadDatabase.any_instance.stub(:save).and_return(false)
        post :create, {:load_database => { "taxonset" => "invalid value" }}, valid_session
        assigns(:load_database).should be_a_new(LoadDatabase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LoadDatabase.any_instance.stub(:save).and_return(false)
        post :create, {:load_database => { "taxonset" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested load_database" do
        load_database = LoadDatabase.create! valid_attributes
        # Assuming there are no other load_databases in the database, this
        # specifies that the LoadDatabase created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LoadDatabase.any_instance.should_receive(:update_attributes).with({ "taxonset" => "MyString" })
        put :update, {:id => load_database.to_param, :load_database => { "taxonset" => "MyString" }}, valid_session
      end

      it "assigns the requested load_database as @load_database" do
        load_database = LoadDatabase.create! valid_attributes
        put :update, {:id => load_database.to_param, :load_database => valid_attributes}, valid_session
        assigns(:load_database).should eq(load_database)
      end

      it "redirects to the load_database" do
        load_database = LoadDatabase.create! valid_attributes
        put :update, {:id => load_database.to_param, :load_database => valid_attributes}, valid_session
        response.should redirect_to(load_database)
      end
    end

    describe "with invalid params" do
      it "assigns the load_database as @load_database" do
        load_database = LoadDatabase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LoadDatabase.any_instance.stub(:save).and_return(false)
        put :update, {:id => load_database.to_param, :load_database => { "taxonset" => "invalid value" }}, valid_session
        assigns(:load_database).should eq(load_database)
      end

      it "re-renders the 'edit' template" do
        load_database = LoadDatabase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LoadDatabase.any_instance.stub(:save).and_return(false)
        put :update, {:id => load_database.to_param, :load_database => { "taxonset" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested load_database" do
      load_database = LoadDatabase.create! valid_attributes
      expect {
        delete :destroy, {:id => load_database.to_param}, valid_session
      }.to change(LoadDatabase, :count).by(-1)
    end

    it "redirects to the load_databases list" do
      load_database = LoadDatabase.create! valid_attributes
      delete :destroy, {:id => load_database.to_param}, valid_session
      response.should redirect_to(load_databases_url)
    end
  end

end
