require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PfitmapReleasesController do
  before do
    @user = get_admin_user
  end

  # This should return the minimal set of attributes required to create a valid
  # PfitmapRelease. As you add validations to PfitmapRelease, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
    release: "1.1",
    release_date: "2005-10-10",
    current: false
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PfitmapReleasesController. Be sure to keep this updated too.
  def valid_session
    {user_id: @user.id}
  end

  describe "GET index" do
    it "assigns all pfitmap_releases as @pfitmap_releases" do
      pfitmap_release = PfitmapRelease.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pfitmap_releases).should eq([pfitmap_release])
    end
  end

  describe "GET show" do
    it "assigns the requested pfitmap_release as @pfitmap_release" do
      pfitmap_release = PfitmapRelease.create! valid_attributes
      get :show, {:id => pfitmap_release.to_param}, valid_session
      assigns(:pfitmap_release).should eq(pfitmap_release)
    end
  end

  describe "GET new" do
    it "assigns a new pfitmap_release as @pfitmap_release" do
      get :new, {}, valid_session
      assigns(:pfitmap_release).should be_a_new(PfitmapRelease)
    end
  end

  describe "GET edit" do
    it "assigns the requested pfitmap_release as @pfitmap_release" do
      pfitmap_release = PfitmapRelease.create! valid_attributes
      get :edit, {:id => pfitmap_release.to_param}, valid_session
      assigns(:pfitmap_release).should eq(pfitmap_release)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PfitmapRelease" do
        expect {
          post :create, {:pfitmap_release => valid_attributes}, valid_session
        }.to change(PfitmapRelease, :count).by(1)
      end

      it "assigns a newly created pfitmap_release as @pfitmap_release" do
        post :create, {:pfitmap_release => valid_attributes}, valid_session
        assigns(:pfitmap_release).should be_a(PfitmapRelease)
        assigns(:pfitmap_release).should be_persisted
      end

      it "redirects to the created pfitmap_release" do
        post :create, {:pfitmap_release => valid_attributes}, valid_session
        response.should redirect_to(PfitmapRelease.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pfitmap_release as @pfitmap_release" do
        # Trigger the behavior that occurs when invalid params are submitted
        PfitmapRelease.any_instance.stub(:save).and_return(false)
        post :create, {:pfitmap_release => {}}, valid_session
        assigns(:pfitmap_release).should be_a_new(PfitmapRelease)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PfitmapRelease.any_instance.stub(:save).and_return(false)
        post :create, {:pfitmap_release => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pfitmap_release" do
        pfitmap_release = PfitmapRelease.create! valid_attributes
        # Assuming there are no other pfitmap_releases in the database, this
        # specifies that the PfitmapRelease created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PfitmapRelease.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => pfitmap_release.to_param, :pfitmap_release => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested pfitmap_release as @pfitmap_release" do
        pfitmap_release = PfitmapRelease.create! valid_attributes
        put :update, {:id => pfitmap_release.to_param, :pfitmap_release => valid_attributes}, valid_session
        assigns(:pfitmap_release).should eq(pfitmap_release)
      end

      it "redirects to the pfitmap_release" do
        pfitmap_release = PfitmapRelease.create! valid_attributes
        put :update, {:id => pfitmap_release.to_param, :pfitmap_release => valid_attributes}, valid_session
        response.should redirect_to(pfitmap_release)
      end
    end

    describe "with invalid params" do
      it "assigns the pfitmap_release as @pfitmap_release" do
        pfitmap_release = PfitmapRelease.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PfitmapRelease.any_instance.stub(:save).and_return(false)
        put :update, {:id => pfitmap_release.to_param, :pfitmap_release => {}}, valid_session
        assigns(:pfitmap_release).should eq(pfitmap_release)
      end

      it "re-renders the 'edit' template" do
        pfitmap_release = PfitmapRelease.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PfitmapRelease.any_instance.stub(:save).and_return(false)
        put :update, {:id => pfitmap_release.to_param, :pfitmap_release => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pfitmap_release" do
      pfitmap_release = PfitmapRelease.create! valid_attributes
      expect {
        delete :destroy, {:id => pfitmap_release.to_param}, valid_session
      }.to change(PfitmapRelease, :count).by(-1)
    end

    it "redirects to the pfitmap_releases list" do
      pfitmap_release = PfitmapRelease.create! valid_attributes
      delete :destroy, {:id => pfitmap_release.to_param}, valid_session
      response.should redirect_to(pfitmap_releases_url)
    end
  end

end
