require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProteinCountsController do

  # This should return the minimal set of attributes required to create a valid
  # ProteinCount. As you add validations to ProteinCount, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProteinCountsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all protein_counts as @protein_counts" do
      protein_count = ProteinCount.create! valid_attributes
      get :index, {}, valid_session
      assigns(:protein_counts).should eq([protein_count])
    end
  end

  describe "GET show" do
    it "assigns the requested protein_count as @protein_count" do
      protein_count = ProteinCount.create! valid_attributes
      get :show, {:id => protein_count.to_param}, valid_session
      assigns(:protein_count).should eq(protein_count)
    end
  end

  describe "GET new" do
    it "assigns a new protein_count as @protein_count" do
      get :new, {}, valid_session
      assigns(:protein_count).should be_a_new(ProteinCount)
    end
  end

  describe "GET edit" do
    it "assigns the requested protein_count as @protein_count" do
      protein_count = ProteinCount.create! valid_attributes
      get :edit, {:id => protein_count.to_param}, valid_session
      assigns(:protein_count).should eq(protein_count)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProteinCount" do
        expect {
          post :create, {:protein_count => valid_attributes}, valid_session
        }.to change(ProteinCount, :count).by(1)
      end

      it "assigns a newly created protein_count as @protein_count" do
        post :create, {:protein_count => valid_attributes}, valid_session
        assigns(:protein_count).should be_a(ProteinCount)
        assigns(:protein_count).should be_persisted
      end

      it "redirects to the created protein_count" do
        post :create, {:protein_count => valid_attributes}, valid_session
        response.should redirect_to(ProteinCount.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved protein_count as @protein_count" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProteinCount.any_instance.stub(:save).and_return(false)
        post :create, {:protein_count => {}}, valid_session
        assigns(:protein_count).should be_a_new(ProteinCount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProteinCount.any_instance.stub(:save).and_return(false)
        post :create, {:protein_count => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested protein_count" do
        protein_count = ProteinCount.create! valid_attributes
        # Assuming there are no other protein_counts in the database, this
        # specifies that the ProteinCount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProteinCount.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => protein_count.to_param, :protein_count => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested protein_count as @protein_count" do
        protein_count = ProteinCount.create! valid_attributes
        put :update, {:id => protein_count.to_param, :protein_count => valid_attributes}, valid_session
        assigns(:protein_count).should eq(protein_count)
      end

      it "redirects to the protein_count" do
        protein_count = ProteinCount.create! valid_attributes
        put :update, {:id => protein_count.to_param, :protein_count => valid_attributes}, valid_session
        response.should redirect_to(protein_count)
      end
    end

    describe "with invalid params" do
      it "assigns the protein_count as @protein_count" do
        protein_count = ProteinCount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProteinCount.any_instance.stub(:save).and_return(false)
        put :update, {:id => protein_count.to_param, :protein_count => {}}, valid_session
        assigns(:protein_count).should eq(protein_count)
      end

      it "re-renders the 'edit' template" do
        protein_count = ProteinCount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProteinCount.any_instance.stub(:save).and_return(false)
        put :update, {:id => protein_count.to_param, :protein_count => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested protein_count" do
      protein_count = ProteinCount.create! valid_attributes
      expect {
        delete :destroy, {:id => protein_count.to_param}, valid_session
      }.to change(ProteinCount, :count).by(-1)
    end

    it "redirects to the protein_counts list" do
      protein_count = ProteinCount.create! valid_attributes
      delete :destroy, {:id => protein_count.to_param}, valid_session
      response.should redirect_to(protein_counts_url)
    end
  end

end
