require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReleasedDbsController do
  let!(:load_database) {FactoryGirl.create(:load_database)}
  let!(:pfitmap_release) {FactoryGirl.create(:pfitmap_release)}
  before do
    @user = get_admin_user
    
  end
  # This should return the minimal set of attributes required to create a valid
  # ReleasedDb. As you add validations to ReleasedDb, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {pfitmap_release_id: pfitmap_release.id, load_database_id: load_database.id } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReleasedDbsController. Be sure to keep this updated too.
  let(:valid_session) { {user_id: @user.id} }
  describe "GET index" do
    it "assigns all released_dbs as @released_dbs" do
      released_db = ReleasedDb.create! valid_attributes
      get :index, {}, valid_session
      assigns(:released_dbs).should eq([released_db])
    end
  end

  describe "GET show" do
    it "assigns the requested released_db as @released_db" do
      released_db = ReleasedDb.create! valid_attributes
      get :show, {:id => released_db.to_param}, valid_session
      assigns(:released_db).should eq(released_db)
    end
  end

  describe "GET new" do
    it "assigns a new released_db as @released_db" do
      get :new, {}, valid_session
      assigns(:released_db).should be_a_new(ReleasedDb)
    end
  end

  describe "GET edit" do
    it "assigns the requested released_db as @released_db" do
      released_db = ReleasedDb.create! valid_attributes
      get :edit, {:id => released_db.to_param}, valid_session
      assigns(:released_db).should eq(released_db)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReleasedDb" do
        expect {
          post :create, {:released_db => valid_attributes}, valid_session
        }.to change(ReleasedDb, :count).by(1)
      end

      it "assigns a newly created released_db as @released_db" do
        post :create, {:released_db => valid_attributes}, valid_session
        assigns(:released_db).should be_a(ReleasedDb)
        assigns(:released_db).should be_persisted
      end

      it "redirects to the created released_db" do
        post :create, {:released_db => valid_attributes}, valid_session
        response.should redirect_to(ReleasedDb.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved released_db as @released_db" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReleasedDb.any_instance.stub(:save).and_return(false)
        post :create, {:released_db => { "pfitmap_release_id" => "invalid value" }}, valid_session
        assigns(:released_db).should be_a_new(ReleasedDb)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReleasedDb.any_instance.stub(:save).and_return(false)
        post :create, {:released_db => { "pfitmap_release_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested released_db" do
        released_db = ReleasedDb.create! valid_attributes
        # Assuming there are no other released_dbs in the database, this
        # specifies that the ReleasedDb created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReleasedDb.any_instance.should_receive(:update_attributes).with({ "pfitmap_release" => "" })
        put :update, {:id => released_db.to_param, :released_db => { "pfitmap_release" => "" }}, valid_session
      end

      it "assigns the requested released_db as @released_db" do
        released_db = ReleasedDb.create! valid_attributes
        put :update, {:id => released_db.to_param, :released_db => valid_attributes}, valid_session
        assigns(:released_db).should eq(released_db)
      end

      it "redirects to the released_db" do
        released_db = ReleasedDb.create! valid_attributes
        put :update, {:id => released_db.to_param, :released_db => valid_attributes}, valid_session
        response.should redirect_to(released_db)
      end
    end

    describe "with invalid params" do
      it "assigns the released_db as @released_db" do
        released_db = ReleasedDb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReleasedDb.any_instance.stub(:save).and_return(false)
        put :update, {:id => released_db.to_param, :released_db => { "pfitmap_release_id" => "invalid value" }}, valid_session
        assigns(:released_db).should eq(released_db)
      end

      it "re-renders the 'edit' template" do
        released_db = ReleasedDb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReleasedDb.any_instance.stub(:save).and_return(false)
        put :update, {:id => released_db.to_param, :released_db => { "pfitmap_release_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested released_db" do
      released_db = ReleasedDb.create! valid_attributes
      expect {
        delete :destroy, {:id => released_db.to_param}, valid_session
      }.to change(ReleasedDb, :count).by(-1)
    end

    it "redirects to the released_dbs list" do
      released_db = ReleasedDb.create! valid_attributes
      delete :destroy, {:id => released_db.to_param}, valid_session
      response.should redirect_to(released_dbs_url)
    end
  end

end
